DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM_PROMPT:
  NAME: "sgd"
  LR: 2e-3
  MOMENTUM: 0.9
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  # WARMUP_EPOCH: 0
  # WARMUP_TYPE: "constant"
  # WARMUP_CONS_LR: 1e-5

OPTIM_CLASSIFIER:
  NAME: "sgd"
  LR: 5e-2
  MOMENTUM: 0.9
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  # WARMUP_EPOCH: 0
  # WARMUP_TYPE: "constant"
  # WARMUP_CONS_LR: 1e-5

OPTIM_ADAPTER:
  NAME: "sgd"
  LR: 1e-2
  MOMENTUM: 0.9
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  # WARMUP_EPOCH: 0
  # WARMUP_TYPE: "constant"
  # WARMUP_CONS_LR: 1e-5
  
TRAIN:
  PRINT_FREQ: 10

TEST:
  DO_TEST: True

MODEL:
  BACKBONE:
    NAME: "RN50"

